### ISSUE TITLE
Terminal color theme

### ISSUE THREAD

**Issue by p-e-w** [pathtrk/ariake-dark-syntax#7]
This theme is beautiful! It would be great if it was available for the most common terminal emulators as well (iTerm2, GNOME Terminal would be a good start) so one can have a consistent look across applications.

I would also like to suggest that you add an image with a palette of all colors. That way, people can easily replicate the theme in other applications themselves without having to dig through the stylesheet to find the values.

As a side note, I was intrigued to read that the theme is "inspired by Japanese traditional colors". Regrettably I am unfamiliar with Japanese culture; could you elaborate a little? Does this set of colors have a name in Japan? Is it linked to some visual arts tradition or style? Really interested to learn more about these amazing colors!

**Comment by GrantRVD** [comment]
@p-e-w : "Ariake" is the first word in the poem cited in the README, the first two kanji. It refers to daybreak, perhaps more specifically to the transition of the moon and night into the light of day, so you may associate it with the soft blue hues you might see at the crack of dawn. The poem itself uses the waning moon at dawn as a bitter metaphor for a lover rejected by his mistress, at least according to many interpretations. So both the colors and the relatively low contrast of theme could be inspired by the aforementioned situation, the "indifference" of the lover mentioned in the poem, or both. At the very least, I'm not aware of any other inspirations for where the theme's name and style could have come from.

**Comment by pathtrk** [comment]
@p-e-w 
Thanks for your feedback!

I don't plan to write a terminal theme nor create a color palette. Please refer styles/colors.less to find which colors are used. There is also my reference of Japanese color. (It is described in Japanese)

http://www.colordic.org/w/

For example, foreground gray is based on 紫水晶 ("Murasaki-Suisho" which means Amethyst) and background black is based on 藍鉄 ("Eye-Tetsu" which means Indigo Steel). But these colors aren't exactly as same as the Japanese traditional color palette because I modified them to fit the text editor in modern age.  The definition of the colors also vary slightly depending on who converts it to digital format.

If you have interest in making a color palette, You can always convert my HSL values on the less file into other format like RGB or HEX.

**Comment by pathtrk** [comment]
If you think the theme needs some extra work with it, Please reopen this issue anytime.

**Comment by p-e-w** [comment]
@GrantRVD, @pathtrk: Thank you both for your responses. I appreciate the insight!

**Comment by ellman121** [comment]
@p-e-w I created a terminal theme for OSX Terminal, you can find it here.   Maybe there's a tool to convert themes for iTerm or something?

https://github.com/ellman121/dotfiles/blob/master/macos/Ariake.terminal
