### ISSUE TITLE
Colors don't look the same 

### ISSUE THREAD

**Issue by ghost** [pathtrk/ariake-dark-syntax#8]
I don't know why but the colors don't look the same for me. It has a grayish tint and it's not bright enough or something. Any idea why? 
![code](https://cloud.githubusercontent.com/assets/3500392/25014050/ff3285ec-202a-11e7-925a-db27975c04b4.png)

Windows 10, 64bit
Atom: 1.16.0

**Comment by pathtrk** [comment]
@blacksky86 
I think the picture you uploaded tells the theme works as I expect. The focused tab has a little more brightness than the other part of the editor window. So it might look like a tint.

The colors can have slight differences on Windows because I created this theme on Mac.

If you improve the color calibration with your monitor, Then the colors of the theme might look more natural too.

**Comment by pathtrk** [comment]
@blacksky86 I'll close this issue for now, but feel free to reopen anytime.
